import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import { Figtree } from "next/font/google";
import "@/styles/globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import BootstrapClient from "@/components/BootstrapClient";
import Navbar from "@/components/Navbar";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Fametonic</title>
        <meta
          name="description"
          content="A platform that helps people turn their social media presence into a profitable career."
        />
        <link rel="icon" href="/icon.ico" />
        <link rel="stylesheet" href="/styles/custom.css" />
      </head>
      <body className={`${figtree.className} `}>
        <Navbar />
        {children}
        <BootstrapClient />
        <Analytics />
      </body>
    </html>
  );
}
